name: Cypress-JS-Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [chrome]
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
      
